---
# This is the config that is fixed for all experiments

# FL training settings
num_clients: 5
num_rounds: 100
fraction_fit: 1.0
min_fit_clients: 5
local_epoch: 1

# Client train/test split
# Let's split it into train (80%) and test (20%)
test_size: 0.2
seed: 1234
