[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "mt-pytorch"
version = "0.1.0"
description = "Multi-Tenant Federated Learning with Flower and PyTorch"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
<<<<<<< HEAD
flwr-nightly = {extras = ["rest", "simulation"], version = "^1.5.0.dev20230705"}
torch = "1.13.1"
torchvision = "0.14.1"
=======
flwr-nightly = { version = "^1.5.0.dev20230629", extras = ["simulation", "rest"] }
# flwr = { path = "../../", develop = true, extras = ["simulation", "rest"] }
torch = "^2.0.1"
torchvision = "^0.15.2"
>>>>>>> origin/main
tqdm = "4.65.0"
