[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "docker-client-driver"
version = "0.1.0"
description = "Running Flower clients using Docker"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
# flwr = { path = "../../", develop = true }  # Development
flwr = ">=1.0,<2.0"
