[package]
name = "flwr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "2.0.0"
futures = "0.3.29"
prost = "0.12.1"
rustls = "0.21.8"
rustls-native-certs = "0.6.3"
tokio = { version = "1.33.0", features = ["full"] }
tokio-stream = "0.1.14"
tonic = { version = "0.10.2", features = ["transport", "tls"] }
uuid = { version = "1.5.0", features = ["v4"] }

[build-dependencies]
tonic-build = "0.10.2"
