name: CI Cache

on:
  push:
    branches:
      - main
  # Remove this section before merging as we
  # only want to populate cache in main
  pull_request:
    branches:
      - main

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  build_python_cache:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # Only use versions found here:
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#python
        # to ensure they are loaded from the runner image hosted tool cache
        # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#hosted-tool-cache
        # By not specifying the patch version it is ensured that a version available in
        # the hosted tool cache is used
        python-version: [
            3.7,
            3.8,
            # 3.9,
            # 3.10
          ]
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap
        id: bootstrap
        uses: ./.github/actions/bootstrap
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m poetry install --all-extras
      - name: Cache Python dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            **/poetry.lock
            **/.venv
            ~/.cache/pip
            ~/.cache/pypoetry
          key: ${{ runner.os }}-python-cache-${{ steps.bootstrap.outputs.python-version }}-${{ hashFiles('**/pyproject.toml') }}
