name: Build docker client image

on:
  workflow_dispatch:
    inputs:
      flwr-version:
        description: "Version of Flower"
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-client-images:
    name: Build client images
    uses: ./.github/workflows/_docker-build.yml
    strategy:
      fail-fast: false
      matrix:
        python: [
          {version: "3.8", tags: "test\n${{ github.event.inputs.flwr-version }}test"},
          {version: "3.9", tags: "test1"}
        ]
    with:
      namespace-repository: flwr/client
      file-dir: src/docker/supernode
      build-args: |
        FLWR_VERSION=1.7.0
        BASE_IMAGE_TAG=py${{ matrix.python.version }}-ubuntu22.04
      tags: ${{matrix.python.tags}}
    secrets:
      dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
