name: Docker Image CI

on:
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: src/docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ./build
