name: Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    

env:
  FLWR_VERSION: 1.5.0

jobs:
  test:
    name: Test Image
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run base tests
      env:
        BUILD_TARGET: base
      run: ./test.sh
    - name: Run server tests
      env:
          BUILD_TARGET: server
      run: ./test.sh

  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the server image
      env:
          BUILD_TARGET: server
      run: ./build.sh
