name: Docker

on:
  push:
    branches:
      - main
    paths:
      -  src/docker/**
  pull_request:
    branches:
      - main
    paths:
      -  src/docker/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: src/docker

jobs:
  test:
    name: Test Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flwr_version: [1.4.0, 1.5.0]
    steps:
    - uses: actions/checkout@v3
    - name: Run server tests
      env:
          BUILD_TARGET: server
          FLWR_VERSION: ${{ matrix.flwr_version }}
      run: ./test.sh

  build:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flwr_version: [1.4.0, 1.5.0]
    steps:
    - uses: actions/checkout@v3
    - name: Build the server image
      env:
          BUILD_TARGET: server
          FLWR_VERSION: ${{ matrix.flwr_version }}
      run: ./build.sh
