name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLWR_TELEMETRY_ENABLED: 0

concurrency:
  # Use github.run_id on main branch
  # Use github.event.pull_request.number on pull requests, so it's unique per pull request
  # Use github.ref on other branches, so it's unique per branch
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_python_docs:
    runs-on: ubuntu-22.04
    name: Build Python Docs
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Install pandoc
        run: sudo apt install pandoc
      - name: Install dependencies (mandatory only)
        run: python -m poetry install --extras "simulation"
      - name: Build docs
        run: ./dev/build-docs.sh

  build_swift_docs:
    runs-on: macos-latest
    name: Build Swift Docs
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Build docs
        run: ./dev/build-swift-api-ref.sh

  deploy_docs:
    needs: ["build_python_docs", "build_swift_docs"]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    name: Deploy 
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Install pandoc
        run: sudo apt install pandoc
      - name: Install dependencies (mandatory only)
        run: python -m poetry install --extras "simulation"
      - name: Build and deploy docs
        env:
          AWS_DEFAULT_REGION: ${{ secrets. AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        run: ./dev/deploy-docs.sh
