name: Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  test_core:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: [3.8.15]
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies (mandatory only)
        run: python -m poetry install --all-extras
        shell: bash
      - name: Check if protos need recompilation
        run: ./dev/check-protos.sh
        shell: bash
      - name: Lint + Test (isort/black/docformatter/mypy/pylint/flake8/pytest)
        run: ./dev/test.sh
        shell: bash
