name: Release

on:
  release:
    types: [published, unpublished]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  build_and_push_server_imgage:
    name: Build and push server image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flwr_version: [1.5.0]
    defaults:
      run:
        working-directory: src/docker
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the server image
      env:
          BUILD_TARGET: server
          FLWR_VERSION: ${{ matrix.flwr_version }}
      run: ./build.sh
